wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.29
    code_path: code/state-of-the-art algorithm/linear_transform_optimize.py
    framework: torch
    is_jupyter_run: false
    python_version: 3.6.10
